# generated by datamodel-codegen:
#   filename:  mint_OBJKT.json
#   timestamp: 2021-03-31T10:54:07+00:00

from __future__ import annotations

from pydantic import BaseModel


class MintObjkt(BaseModel):
    address: str
    amount: str
    metadata: str
    royalties: str
