# generated by datamodel-codegen:
#   filename:  cancel_swap.json
#   timestamp: 2021-04-01T05:48:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class CancelSwap(BaseModel):
    __root__: str
