# generated by datamodel-codegen:
#   filename:  collect.json
#   timestamp: 2021-04-01T05:48:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class Collect(BaseModel):
    objkt_amount: str
    swap_id: str
