# generated by datamodel-codegen:
#   filename:  curate.json
#   timestamp: 2021-04-01T05:48:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class Curate(BaseModel):
    hDAO_amount: str
    objkt_id: str
