# generated by datamodel-codegen:
#   filename:  genesis.json
#   timestamp: 2021-04-01T05:48:10+00:00

from __future__ import annotations

from pydantic import BaseModel


class Genesis(BaseModel):
    pass
