# generated by datamodel-codegen:
#   filename:  swap.json
#   timestamp: 2021-04-01T05:48:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class Swap(BaseModel):
    objkt_amount: str
    objkt_id: str
    xtz_per_objkt: str
