# generated by datamodel-codegen:
#   filename:  update_manager.json
#   timestamp: 2021-04-01T05:48:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class UpdateManager(BaseModel):
    __root__: str
