# generated by datamodel-codegen:
#   filename:  balance_of.json
#   timestamp: 2021-04-01T05:48:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Request(BaseModel):
    owner: str
    token_id: str


class BalanceOf(BaseModel):
    requests: List[Request]
    callback: str
