# generated by datamodel-codegen:
#   filename:  set_administrator.json
#   timestamp: 2021-04-01T05:48:07+00:00

from __future__ import annotations

from pydantic import BaseModel


class SetAdministrator(BaseModel):
    __root__: str
