# generated by datamodel-codegen:
#   filename:  set_pause.json
#   timestamp: 2021-04-01T05:48:09+00:00

from __future__ import annotations

from pydantic import BaseModel


class SetPause(BaseModel):
    __root__: bool
