# generated by datamodel-codegen:
#   filename:  token_metadata.json
#   timestamp: 2021-04-01T05:48:08+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class TokenMetadata(BaseModel):
    token_ids: List[str]
    handler: str
