# generated by datamodel-codegen:
#   filename:  transfer.json
#   timestamp: 2021-04-01T05:48:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class Tx(BaseModel):
    to_: str
    token_id: str
    amount: str


class TransferItem(BaseModel):
    from_: str
    txs: List[Tx]


class Transfer(BaseModel):
    __root__: List[TransferItem]
