database:
  path: /home/droserasprout/git/pytezos/db.sqlite3
tzkt:
  url: https://api.tzkt.io
contracts:
  HEN_minter: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
handlers:
  - contract: HEN_minter
    entrypoint: mint
    handler: on_mint
debug: True