module: pytezos_dapps.dapps.hic_et_nunc
database:
  connection_string: sqlite:///home/droserasprout/git/pytezos/db.sqlite3
tzkt:
  url: https://api.tzkt.io
contract: KT1Hkg5qeNhfwpKW4fXvq7HGZB9z2EnmCCA9
handlers:
  mint: on_mint